package controller;

public enum Actions {
	MUSESTACK_WINDOW, PLATFORM_ARTIST, PLATFORM_USER, PLATFORM_ADMINISTRATOR, PANEL_LOGIN_USER, PANEL_INITIAL_USER, PANEL_USER_REGISTER,
	PANEL_USER_EVENTS, PANEL_USER_ARTISTS, PANEL_USER_PICTURES,
	READFILE, WRITE_BINARY_FILE;
}