package controller;

public enum Actions {
	MUSESTACK_WINDOW,
	PLATFORM_ARTIST,
	PLATFORM_USER,
	PLATFORM_ADMINISTRATOR,
	PANEL_LOGIN_USER,
	PANEL_INITIAL_USER,
	PANEL_INITIAL_ARTIST,
	PANEL_INITIAL_ADMIN,
	PANEL_USER_REGISTER,
	PANEL_USER_EVENTS,
	PANEL_USER_ARTISTS,
	PANEL_USER_PICTURES,
	PANEL_USER_ARTIST_PICTURE,
	PANEL_CALIFICATION,
	PANEL_USER_INFO,
	PANEL_TOP_CALIFICATIONS,
	LOGIN_ARTIST, LOGIN_ADMIN,
	OPEN_FACEBOOK,
	OPEN_TWITER,
	OPEN_INSTAGRAM,
	READFILE,
	WRITE_BINARY_FILE,
	GRAPH_ARTIST_BY_GENRE;
}